name: Build Windows EXE

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          
      - name: Install dependencies
        run: flutter pub get
        
      - name: Enable Windows desktop
        run: flutter config --enable-windows
        
      - name: Build Windows EXE
        run: |
          flutter build windows --release
          ls -R build/windows/runner/Release/  # 调试：列出构建目录内容
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: build/windows/runner/Release/
          if-no-files-found: error  # 如果没有文件则报错